DROP TABLE IF EXISTS appointment_notes;
--;;
DROP TABLE IF EXISTS appointment_needs;
--;;
DROP TABLE IF EXISTS appointments;
--;;
DROP TABLE IF EXISTS availabilities;
--;;
DROP TABLE IF EXISTS needs;
--;;
DROP TABLE IF EXISTS contacts;
--;;
DROP TABLE IF EXISTS invitations;
--;;
DROP TABLE IF EXISTS users;