DROP TABLE IF EXISTS careseekers;
--;;
DROP TABLE IF EXISTS providers;
--;;
DROP TABLE IF EXISTS appointments;
--;;
DROP TABLE IF EXISTS availabilities;
--;;
DROP TABLE IF EXISTS needs;
--;;
DROP TABLE IF EXISTS fulfillments;
--;;
DROP TABLE IF EXISTS contacts;